<?php

include_once('bleen.features.inc');

/**
 * Implements hook_block_info().
 */
function bleen_block_info() {
  $blocks = array();
  $blocks['bleen_definition'] = array(
    'info'    => t('Definition of Bleen'),
    'cache'   => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bleen_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'bleen_definition':
      $block['subject'] = t('What is Bleen?');
      $block['content'] = array('#markup' => variable_get('bleen_definition', ''));
      break;
  }

  return $block;
}

function bleen_contextual_links_view_alter(&$element, &$items) {
  // This hook is called for EVERY set of contextual links on a page.  We first
  // want to check the $element to make sure we are adding a link to the correct
  // list of contextual links. In this case we only want to add a link to blocks
  // created by the "search" module. We just add links using the same array
  // structure as is used by theme_links.
  // Note: changed $element to $element['#element'] and make URLs absolute.
  if (isset($element['#element']['#block']) && $element['#element']['#block']->module == "bleen" && $element['#element']['#block']->delta == "bleen_definition"){
    $element['#links']['bleen'] = array(
      'title' => 'Edit definition',
      'href' => url('/admin/config/system/site-information', array('absolute' => TRUE)),
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bleen_form_system_site_information_settings_alter(&$form, $form_state) {
  $form['site_information']['site_slogan']['#access'] = FALSE;
  $form['site_information']['bleen_definition'] = array(
    '#type'           => 'text_format',
    '#title'          => t('Definition of Bleen'),
    '#default_value'  => variable_get('bleen_definition', ''),
    '#description'    => t('Define the word "Bleen".'),
  );
  $form['#submit'][] = 'bleen_form_system_site_information_submit';
}

/**
 * Form submit function.
 */
function bleen_form_system_site_information_submit($form, $form_state) {
  variable_set('bleen_definition', $form_state['values']['bleen_definition']['value']);
}

